### PR TITLE
GMCP Support and client-side generated prompts.

### PR DESCRIPTION
**Pull request by georgestephanis**
The client-side prompt functionality can enable such functionality as:

Screenshot 2022-12-14 at 9 23 34 AM

Screenshot 2022-12-14 at 9 27 02 AM

Screenshot 2022-12-14 at 9 28 26 AM

Screenshot 2022-12-14 at 9 36 29 AM

* Inserting your character name dynamically into the prompt, useful for if copy-pasting logs out of your client
* Dynamically inserting a line about your current droid (if you have one) and its status
* Inserting your current planet and room data
* Time and Ambiance
* If you're a forcer, putting a link you can click on to meditate if you're at less than full health
* If you're in a ship, putting data about your ship's status and location in your prompt (very useful when reviewing space battles after the fact, or just situational awareness)
* Customizable combat prompts, including specifying who your current combat target is (useful in group fights if folks are rescuing or you're getting jumped by mobs)

### CODE REVIEW

**Comment by georgestephanis** [comment]
In a future update, I'm going to add commands to configure the color scheme of the prompt via aliases, rather than having it hardcoded.

However, for now if desired you can override them here:

https://github.com/Xavious/LotjClient/pull/28/files#diff-fc9e1a8dc8b52d457099e566bc7869e6bd5563dd39678e3f496e28a7ecdca1c3R131-R132

**Comment by georgestephanis** [comment]
The custom prompt is not only to act as a token to be replaced, but also injects a number of variables to be parsed by the replacer that are unavailable in gmcp/msdp

**Comment by georgestephanis** [comment]
These are the things I have it pulling from the prompt to supplant the out-of-band variables being passed --

```
{
  "PeopleNear": "%A",
  "TimeOfDay": "%W",
  "Ambience": "%J",
  "Tone": "%D",
  "Language": "%w",
  "Action": "%g",
  "Droid": "%d",
  "DroidHP": "%s",
  "MentalState": "%G",
  "CurrUsers": "%u",
  "EnemyHP": "%E"
}
```

The EnemyHP pulls from the prompt as occasionally the msdp/gmcp vars can get slightly delayed or out of sync, so it's nicer to pull from there, and can be an indicator for being in combat or not.

**Comment by georgestephanis** [comment]
Also, MSDP could be used for a lot of this instead of GMCP, however GMCP does a better job with clearing the variables when they are unset client-side, whereas MSDP will just let the planet name (for example) ride even when you're in space or a ship until there's a new planet name that is passed to override it.

In short, msdp doesn't unset some values when they clear the same way gmcp does.

**Comment by Xavious** [comment]
@georgestephanis merged. Currently this will just put the files in the plugins folder. I could create a version that pre-adds these, but I have to admit I'm a tad ignorant to what these are doing except on a very surface level. Maybe we can talk that out later.

**Pull request merged**
